"""Time-based One-Time Password (TOTP) helpers (RFC 6238).

Implemented in pure stdlib — we don't want a third-party dependency
just for treasury withdrawal gating. The algorithm is:

1. A shared secret (base32-encoded random bytes) is generated by
   :func:`generate_secret` and shown to the admin once (QR + manual
   copy).
2. Apps like Google Authenticator / 1Password compute
   ``HMAC-SHA1(secret, floor(unix_time / 30))`` and present the low
   6 digits of a dynamic-truncated word.
3. The server runs the same computation and accepts the code if it
   matches the previous, current or next 30-second window.

The dependency :func:`require_totp` decodes a ``X-Totp-Code`` request
header and verifies it against ``user.totp_secret``. Endpoints that
must be 2FA-gated (treasury withdrawal, user delete) add it to their
dependency list — it returns the resolved ``User`` so handlers don't
have to depend on both ``AdminUser`` and the TOTP check.

**NTP / PTP requirement.** TOTP is fundamentally a
clock-comparison protocol: the server and the user's authenticator
app must agree on ``floor(unix_time / 30)`` (modulo the
±``_DRIFT_WINDOWS`` tolerance). With ``_DRIFT_WINDOWS = 1`` we admit
codes from the previous, current, and next 30-second windows, so the
server tolerates roughly ±60 seconds of skew against the
authenticator. Beyond that, valid codes typed in good faith by the
admin will start to 401 and treasury withdrawals will silently fail.

Operational requirements:

* **Production / staging hosts MUST run an NTP client** (``chrony``,
  ``systemd-timesyncd``, or any RFC 5905 implementation) syncing to
  a stratum-1 or stratum-2 pool. Cloud VMs typically get this for
  free via the hypervisor; bare-metal deployments must opt in.
* On hosts behind a strict NAT / air-gapped network, run a local NTP
  server (e.g. ``chronyd`` against an in-VPC clock source) rather
  than disabling sync.
* **PTP (Precision Time Protocol) is overkill** for our use case
  — NTP's typical sub-100ms accuracy is already 600× tighter than
  the 60s drift window. We only mention PTP here because hyperscaler
  deployments with a PHC-backed clock should NOT be downgraded to
  plain NTP just to match this code; both work.
* If you must skew the clock for debugging (e.g. ``date -s``), the
  TOTP cache in Redis (``totp-claim:{user.id}:{matched}``) will keep
  the previously-accepted counter pinned. After fixing the clock,
  flush those keys: ``redis-cli --scan --pattern 'totp-claim:*' |
  xargs redis-cli del``.

The ``_DRIFT_WINDOWS`` value is intentionally NOT plumbed through to
the ``Settings`` class — widening it weakens replay protection (a
wider acceptance window means an attacker has longer to reuse a
shoulder-surfed code) and tightening it just causes false rejects.
Fix the clock instead.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import logging
import os
import secrets
import struct
import time
from datetime import UTC, datetime, timedelta
from urllib.parse import quote

import jwt
from fastapi import HTTPException
from sqlalchemy import or_, update
from sqlalchemy.ext.asyncio import AsyncSession

from .config import pin_secret, settings
from .models import User
from .redis_client import get_redis

_TOTP_SESSION_JWT_ALGORITHM = "HS256"
_TOTP_SESSION_JWT_ISSUER = "garant-totp"

logger = logging.getLogger(__name__)

# Default RFC 6238 parameters (we keep them in sync with the popular
# authenticator apps).
_DIGITS = 6
_PERIOD = 30
_DRIFT_WINDOWS = 1


def generate_secret(num_bytes: int = 20) -> str:
    """Return a fresh base32-encoded secret of ``num_bytes * 8`` bits."""
    raw = secrets.token_bytes(num_bytes)
    return base64.b32encode(raw).decode("ascii").rstrip("=")


def _b32decode_padded(secret: str) -> bytes:
    secret = secret.upper().strip().replace(" ", "")
    pad = (-len(secret)) % 8
    return base64.b32decode(secret + "=" * pad, casefold=True)


def _hotp(key: bytes, counter: int) -> str:
    counter_bytes = struct.pack(">Q", counter)
    digest = hmac.new(key, counter_bytes, hashlib.sha1).digest()
    offset = digest[-1] & 0x0F
    code_int = (
        ((digest[offset] & 0x7F) << 24)
        | ((digest[offset + 1] & 0xFF) << 16)
        | ((digest[offset + 2] & 0xFF) << 8)
        | (digest[offset + 3] & 0xFF)
    )
    code = code_int % (10**_DIGITS)
    return str(code).zfill(_DIGITS)


def totp_now(secret: str, *, at: float | None = None) -> str:
    """Compute the TOTP code for ``secret`` at the given time (defaults to now)."""
    if at is None:
        at = time.time()
    counter = int(at) // _PERIOD
    return _hotp(_b32decode_padded(secret), counter)


def verify_totp(secret: str, code: str, *, at: float | None = None) -> bool:
    """Constant-time check of ``code`` against ``secret``.

    Accepts the previous, current and next 30s windows (``±_DRIFT_WINDOWS``)
    to tolerate clock skew.

    Does **not** prevent replay — use :func:`verify_totp_and_counter` for
    that, which also returns the accepted counter so the caller can
    persist it and reject reuse.
    """
    return verify_totp_and_counter(secret, code, at=at) is not None


def verify_totp_and_counter(secret: str, code: str, *, at: float | None = None) -> int | None:
    """Return the counter for the matching window, or ``None`` if the
    code doesn't verify.

    The caller is expected to compare the returned counter against the
    user's stored high-water mark (``users.totp_last_counter``) and
    reject codes ``<=`` that to prevent replay within the same 30-second
    window (per RFC 6238 §5.2).
    """
    if not secret or not code:
        return None
    code = code.strip()
    if not code.isdigit() or len(code) != _DIGITS:
        return None
    if at is None:
        at = time.time()
    counter = int(at) // _PERIOD
    key = _b32decode_padded(secret)
    # Audit M-5 — exhaust the full ``2 * _DRIFT_WINDOWS + 1`` range
    # before returning. ``hmac.compare_digest`` itself is constant-time
    # per comparison, but a ``for ... if compare_digest(...): return``
    # loop leaks *which* window matched through wall-clock timing on
    # the server response (an attacker who can observe response time
    # and predict ``_PERIOD`` can binary-search the drift offset).
    # The risk is small at ``_DRIFT_WINDOWS == 1`` but the pattern is
    # an anti-pattern for crypto verification, so we always do every
    # comparison and only remember the first match.
    matched_counter: int | None = None
    for delta in range(-_DRIFT_WINDOWS, _DRIFT_WINDOWS + 1):
        candidate_counter = counter + delta
        candidate = _hotp(key, candidate_counter)
        # Always invoke ``compare_digest`` so we walk the full window
        # before returning; reorder the boolean so the
        # ``matched_counter is None`` short-circuit can't skip the
        # comparison itself.
        matched_now = hmac.compare_digest(candidate, code)
        if matched_now and matched_counter is None:
            matched_counter = candidate_counter
    return matched_counter


def otpauth_url(secret: str, *, account: str, issuer: str = "Garant") -> str:
    """Return an ``otpauth://`` URL suitable for QR generation."""
    label = quote(f"{issuer}:{account}", safe="")
    return (
        f"otpauth://totp/{label}"
        f"?secret={secret}"
        f"&issuer={quote(issuer)}"
        f"&algorithm=SHA1"
        f"&digits={_DIGITS}"
        f"&period={_PERIOD}"
    )


# ``ADMIN_TOTP_BYPASS`` short-circuits the entire TOTP
# check when a matching ``X-Totp-Code`` header arrives. Used by the
# integration test suite so e2e tests don't have to provision a real
# TOTP secret; in production this must be unset.
#
# Read it via a function (NOT a module-level constant) so:
#
# 1. Each request re-fetches the current value, which makes
#    ``monkeypatch.setenv``/``delenv`` in tests work without having
#    to reload the module.
# 2. A misconfigured production deploy can be detected and shut down
#    by external tooling that mutates the env between requests —
#    e.g. an operator setting it to ``""`` while the process is
#    running will take effect on the next admin call, not on the
#    next restart.
#
# A loud WARNING is logged at module import / app startup whenever
# this var is non-empty so the bypass shows up in CloudWatch /
# stdout for every boot, not just on the request that exercises it.
def _totp_bypass() -> str:
    """Return the current ``ADMIN_TOTP_BYPASS`` value, or ``""`` if unset.

    Fails closed in production/staging: even when the env var leaks
    into a prod host (CI value copy-pasted, container image baked
    with the staging value, etc.) this function returns ``""`` so the
    bypass NEVER short-circuits ``_consume_totp``. Mirrors the
    fail-closed pattern of
    :func:`backend.app.security._parse_unsigned` and
    :func:`backend.app.config.pin_secret` — a loud WARNING at boot
    was the only previous defence, and it was advisory-only.
    """
    value = os.environ.get("ADMIN_TOTP_BYPASS") or ""
    if value and settings.environment in ("production", "staging"):
        # Per-call ERROR (not just import-time) so a leak is
        # impossible to miss in CloudWatch / Loki.
        logger.error(
            "ADMIN_TOTP_BYPASS is set in environment=%s — refusing to honour it",
            settings.environment,
            extra={"event": "auth_2fa.bypass.rejected_in_prod"},
        )
        return ""
    return value


if os.environ.get("ADMIN_TOTP_BYPASS"):
    # Startup-time log; intentionally NOT logging the value itself
    # (would defeat the point of treating it as a shared secret in
    # CI logs). V11-L-15 — structured-logging fields so the
    # JSON-logger downstream (Loki/Sentry) can pivot on event
    # without regexing the message body. In prod/staging we log
    # ERROR so the alerting pipeline fires; in dev/test we keep the
    # historical WARNING level.
    if settings.environment in ("production", "staging"):
        logger.error(
            "ADMIN_TOTP_BYPASS is set in environment=%s — bypass is "
            "disabled (fail-closed). Unset the env var.",
            settings.environment,
            extra={"event": "auth_2fa.bypass.disabled_in_prod"},
        )
    else:
        logger.warning(
            "ADMIN_TOTP_BYPASS is set — 2FA is bypassed for matching "
            "X-Totp-Code headers. This MUST NOT be set in production.",
            extra={"event": "auth_2fa.bypass.enabled"},
        )


async def _consume_totp(session: AsyncSession, user: User, code: str | None) -> None:
    """Verify ``code`` against ``user.totp_secret`` and atomically bump
    ``totp_last_counter`` so the same code can't be replayed inside its
    30-second window.

    Raises 401 on missing/invalid code, 403 if TOTP isn't configured.
    The bypass env var (``ADMIN_TOTP_BYPASS``) short-circuits both
    checks for e2e tests — V5-A-9 (L) re-reads it per-request via
    :func:`_totp_bypass` so operator-side ``unset`` takes effect on
    the next request without a process restart.
    """
    bypass = _totp_bypass()
    if bypass and code and hmac.compare_digest(code, bypass):
        # Constant-time compare so the bypass token cannot be
        # recovered byte-by-byte via response-timing analysis (the
        # rest of this module is careful about constant-time crypto
        # — see ``verify_totp_and_counter`` and the comment above
        # the ``hmac.compare_digest`` call there).
        return
    if not user.totp_enabled or not user.totp_secret:
        raise HTTPException(
            403,
            {"code": "totp_not_configured", "detail": "2FA не настроен — пройдите настройку 2FA"},
        )
    if not code:
        raise HTTPException(401, {"code": "totp_required", "detail": "Введите код 2FA"})
    matched = verify_totp_and_counter(user.totp_secret, code)
    if matched is None:
        raise HTTPException(401, {"code": "totp_invalid", "detail": "Неверный код 2FA"})
    if matched <= (user.totp_last_counter or -1):
        # Replay: code already accepted in this (or an earlier) window.
        raise HTTPException(
            401,
            {"code": "totp_replay", "detail": "Код 2FA уже использован — дождитесь следующего"},
        )
    # claim the counter in Redis BEFORE we trust the DB
    # commit. Pre-fix, replay protection lived only in
    # ``users.totp_last_counter`` which the caller would persist
    # later via ``session.commit()``. If two parallel withdrawal
    # requests both passed verification before either commit landed,
    # they would both see the OLD high-water mark and both succeed —
    # i.e. a 30-second replay window for a stolen code. ``SET NX EX``
    # in Redis is an atomic claim that holds for the full TOTP
    # period plus a small drift buffer, so the second request
    # immediately 401s without touching the DB. When Redis is
    # disabled we fall back to the DB counter — see below for the
    # conditional UPDATE that closes the corresponding RMW race.
    r = await get_redis()
    redis_claimed = False
    if r is not None:
        try:
            key = f"totp-claim:{user.id}:{matched}"
            # Hold for one full period on each side of ``matched``
            # (covers ``_DRIFT_WINDOWS=1``) plus a safety second.
            claimed = await r.set(
                key,
                "1",
                nx=True,
                ex=_PERIOD * (2 * _DRIFT_WINDOWS + 1) + 1,
            )
            if not claimed:
                _d = "Код 2FA уже использован — дождитесь следующего"
                raise HTTPException(
                    401,
                    {"code": "totp_replay", "detail": _d},
                )
            redis_claimed = True
        except HTTPException:
            raise
        except Exception:
            # Redis hiccup: if the operator has opted into strict
            # mode (``require_redis_for_2fa``), fail closed rather
            # than fall back to the lossy DB-counter path. The
            # alternative — falling through — is only safe in
            # single-worker deployments because the DB-counter
            # update below is a last-writer-wins RMW with no
            # conditional WHERE, so two concurrent commits can both
            # observe the old counter and accept the same code.
            logger.exception(
                "auth_2fa: redis totp-claim failed; using DB fallback",
                extra={
                    "event": "auth_2fa.redis.failed",
                    "user_id": user.id,
                },
            )
            if settings.require_redis_for_2fa:
                raise HTTPException(  # noqa: B904
                    503,
                    {
                        "code": "totp_unavailable",
                        "detail": "Сервис 2FA временно недоступен",
                    },
                )
    # DB-side counter bump. Always use a conditional UPDATE so two
    # concurrent admins (or two parallel calls from the same admin)
    # that both pass the in-memory ``matched > totp_last_counter``
    # check above cannot both win the commit: the second UPDATE
    # ticks ``rowcount == 0`` and we treat that as a replay. This
    # closes the Redis-fallback race documented above.
    if not redis_claimed:
        result = await session.execute(
            update(User)
            .where(
                User.id == user.id,
                or_(
                    User.totp_last_counter.is_(None),
                    User.totp_last_counter < matched,
                ),
            )
            .values(totp_last_counter=matched)
        )
        if (result.rowcount or 0) == 0:
            raise HTTPException(
                401,
                {
                    "code": "totp_replay",
                    "detail": "Код 2FA уже использован — дождитесь следующего",
                },
            )
        # Keep the ORM-managed object in sync with the conditional
        # UPDATE so the caller's later attribute reads see the new
        # high-water mark without a refresh round-trip.
        user.totp_last_counter = matched
    else:
        user.totp_last_counter = matched
        session.add(user)


# ``TotpUser`` lives in :mod:`backend.app.admin_guard` now (R2 —
# unified admin dependency). Importing it back here would create a
# circular import (``admin_guard`` imports ``_consume_totp`` from this
# module). Routers should ``from .admin_guard import TotpUser`` going
# forward.


def issue_totp_session_token(user_id: int, epoch: int = 0) -> tuple[str, datetime]:
    """Mint a ``X-Totp-Session`` JWT that gates admin TOTP for 24h.

    The JWT embeds ``users.totp_session_epoch`` at issue time. Bumping
    that column (``2fa.disable``, re-enable, admin
    ``invalidate-sessions``) immediately invalidates every outstanding
    session without waiting for the TTL — same pattern as the PIN
    session epoch. We sign with ``pin_secret()`` so a single rotation
    of the JWT key wipes both surfaces.
    """
    now = datetime.now(UTC)
    expires = now + timedelta(seconds=settings.totp_session_ttl_seconds)
    payload = {
        "sub": str(user_id),
        "iss": _TOTP_SESSION_JWT_ISSUER,
        "iat": int(now.timestamp()),
        "exp": int(expires.timestamp()),
        "jti": secrets.token_hex(8),
        "epoch": int(epoch),
    }
    token = jwt.encode(payload, pin_secret(), algorithm=_TOTP_SESSION_JWT_ALGORITHM)
    return token, expires


def decode_totp_session_token(token: str) -> tuple[int, int] | None:
    """Return ``(user_id, epoch)`` for a valid TOTP-session JWT, or ``None``.

    Mirrors :func:`backend.app.pin.decode_session_token` for the
    parallel TOTP surface. The caller compares ``epoch`` against the
    user's current ``totp_session_epoch`` to enforce
    admin-initiated invalidation.
    """
    try:
        payload = jwt.decode(
            token,
            pin_secret(),
            algorithms=[_TOTP_SESSION_JWT_ALGORITHM],
            issuer=_TOTP_SESSION_JWT_ISSUER,
        )
    except jwt.PyJWTError:
        return None
    sub = payload.get("sub")
    if not sub:
        return None
    try:
        user_id = int(sub)
    except (TypeError, ValueError):
        return None
    raw_epoch = payload.get("epoch", 0)
    try:
        epoch = int(raw_epoch)
    except (TypeError, ValueError):
        return None
    return user_id, epoch


def validate_totp_session(user: User, token: str | None) -> bool:
    """Return ``True`` if ``token`` is a live TOTP session for ``user``.

    Used by :class:`backend.app.admin_guard.AdminGuard` to decide
    whether to short-circuit the ``X-Totp-Code`` consumption path. The
    function is intentionally pure (no DB writes) so it can run on
    every admin request without amplifying the write load.
    """
    if not token:
        return False
    decoded = decode_totp_session_token(token)
    if decoded is None:
        return False
    token_user_id, token_epoch = decoded
    if token_user_id != user.id:
        return False
    if token_epoch != int(user.totp_session_epoch or 0):
        return False
    # 2FA must still be enabled on the account — disabling it bumps
    # ``totp_session_epoch`` but we double-check ``totp_enabled`` here
    # so a user who clears their TOTP secret cannot reach 2FA-gated
    # endpoints with a stale-but-epoch-matched session.
    if not user.totp_enabled:
        return False
    return True
