"""Time-based One-Time Password (TOTP) helpers (RFC 6238).

Implemented in pure stdlib — we don't want a third-party dependency
just for treasury withdrawal gating. The algorithm is:

1. A shared secret (base32-encoded random bytes) is generated by
   :func:`generate_secret` and shown to the admin once (QR + manual
   copy).
2. Apps like Google Authenticator / 1Password compute
   ``HMAC-SHA1(secret, floor(unix_time / 30))`` and present the low
   6 digits of a dynamic-truncated word.
3. The server runs the same computation and accepts the code if it
   matches the previous, current or next 30-second window.

The dependency :func:`require_totp` decodes a ``X-Totp-Code`` request
header and verifies it against ``user.totp_secret``. Endpoints that
must be 2FA-gated (treasury withdrawal, user delete) add it to their
dependency list — it returns the resolved ``User`` so handlers don't
have to depend on both ``AdminUser`` and the TOTP check.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
import struct
import time
from typing import Annotated
from urllib.parse import quote

from fastapi import Depends, Header, HTTPException

from .deps import AdminUser
from .models import User

# Default RFC 6238 parameters (we keep them in sync with the popular
# authenticator apps).
_DIGITS = 6
_PERIOD = 30
_DRIFT_WINDOWS = 1


def generate_secret(num_bytes: int = 20) -> str:
    """Return a fresh base32-encoded secret of ``num_bytes * 8`` bits."""
    raw = secrets.token_bytes(num_bytes)
    return base64.b32encode(raw).decode("ascii").rstrip("=")


def _b32decode_padded(secret: str) -> bytes:
    secret = secret.upper().strip().replace(" ", "")
    pad = (-len(secret)) % 8
    return base64.b32decode(secret + "=" * pad, casefold=True)


def _hotp(key: bytes, counter: int) -> str:
    counter_bytes = struct.pack(">Q", counter)
    digest = hmac.new(key, counter_bytes, hashlib.sha1).digest()
    offset = digest[-1] & 0x0F
    code_int = (
        ((digest[offset] & 0x7F) << 24)
        | ((digest[offset + 1] & 0xFF) << 16)
        | ((digest[offset + 2] & 0xFF) << 8)
        | (digest[offset + 3] & 0xFF)
    )
    code = code_int % (10**_DIGITS)
    return str(code).zfill(_DIGITS)


def totp_now(secret: str, *, at: float | None = None) -> str:
    """Compute the TOTP code for ``secret`` at the given time (defaults to now)."""
    if at is None:
        at = time.time()
    counter = int(at) // _PERIOD
    return _hotp(_b32decode_padded(secret), counter)


def verify_totp(secret: str, code: str, *, at: float | None = None) -> bool:
    """Constant-time check of ``code`` against ``secret``.

    Accepts the previous, current and next 30s windows (``±_DRIFT_WINDOWS``)
    to tolerate clock skew.
    """
    if not secret or not code:
        return False
    code = code.strip()
    if not code.isdigit() or len(code) != _DIGITS:
        return False
    if at is None:
        at = time.time()
    counter = int(at) // _PERIOD
    key = _b32decode_padded(secret)
    for delta in range(-_DRIFT_WINDOWS, _DRIFT_WINDOWS + 1):
        candidate = _hotp(key, counter + delta)
        if hmac.compare_digest(candidate, code):
            return True
    return False


def otpauth_url(secret: str, *, account: str, issuer: str = "Garant") -> str:
    """Return an ``otpauth://`` URL suitable for QR generation."""
    label = quote(f"{issuer}:{account}", safe="")
    return (
        f"otpauth://totp/{label}"
        f"?secret={secret}"
        f"&issuer={quote(issuer)}"
        f"&algorithm=SHA1"
        f"&digits={_DIGITS}"
        f"&period={_PERIOD}"
    )


# Environment override — when set, bypasses TOTP entirely so e2e tests
# can exercise treasury endpoints without provisioning a real secret.
_TOTP_BYPASS = os.environ.get("ADMIN_TOTP_BYPASS") or ""


async def require_totp(
    user: AdminUser,
    x_totp_code: Annotated[str | None, Header(alias="X-Totp-Code")] = None,
) -> User:
    """FastAPI dependency that gates a route behind a valid TOTP code.

    Returns the resolved admin ``User`` so handlers don't have to
    re-declare ``AdminUser``. Raises 403 if TOTP isn't configured for
    the actor; 401 if the code is wrong / missing.
    """
    if _TOTP_BYPASS:
        if x_totp_code == _TOTP_BYPASS:
            return user
    if not user.totp_enabled or not user.totp_secret:
        raise HTTPException(403, "2FA не настроен — пройдите настройку 2FA")
    if not x_totp_code:
        raise HTTPException(401, "Введите код 2FA")
    if not verify_totp(user.totp_secret, x_totp_code):
        raise HTTPException(401, "Неверный код 2FA")
    return user


TotpUser = Annotated[User, Depends(require_totp)]
