"""Time-based One-Time Password (TOTP) helpers (RFC 6238).

Implemented in pure stdlib — we don't want a third-party dependency
just for treasury withdrawal gating. The algorithm is:

1. A shared secret (base32-encoded random bytes) is generated by
   :func:`generate_secret` and shown to the admin once (QR + manual
   copy).
2. Apps like Google Authenticator / 1Password compute
   ``HMAC-SHA1(secret, floor(unix_time / 30))`` and present the low
   6 digits of a dynamic-truncated word.
3. The server runs the same computation and accepts the code if it
   matches the previous, current or next 30-second window.

The dependency :func:`require_totp` decodes a ``X-Totp-Code`` request
header and verifies it against ``user.totp_secret``. Endpoints that
must be 2FA-gated (treasury withdrawal, user delete) add it to their
dependency list — it returns the resolved ``User`` so handlers don't
have to depend on both ``AdminUser`` and the TOTP check.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
import struct
import time
from typing import Annotated
from urllib.parse import quote

from fastapi import Depends, Header, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from .deps import AdminUser, SessionDep
from .models import User

# Default RFC 6238 parameters (we keep them in sync with the popular
# authenticator apps).
_DIGITS = 6
_PERIOD = 30
_DRIFT_WINDOWS = 1


def generate_secret(num_bytes: int = 20) -> str:
    """Return a fresh base32-encoded secret of ``num_bytes * 8`` bits."""
    raw = secrets.token_bytes(num_bytes)
    return base64.b32encode(raw).decode("ascii").rstrip("=")


def _b32decode_padded(secret: str) -> bytes:
    secret = secret.upper().strip().replace(" ", "")
    pad = (-len(secret)) % 8
    return base64.b32decode(secret + "=" * pad, casefold=True)


def _hotp(key: bytes, counter: int) -> str:
    counter_bytes = struct.pack(">Q", counter)
    digest = hmac.new(key, counter_bytes, hashlib.sha1).digest()
    offset = digest[-1] & 0x0F
    code_int = (
        ((digest[offset] & 0x7F) << 24)
        | ((digest[offset + 1] & 0xFF) << 16)
        | ((digest[offset + 2] & 0xFF) << 8)
        | (digest[offset + 3] & 0xFF)
    )
    code = code_int % (10**_DIGITS)
    return str(code).zfill(_DIGITS)


def totp_now(secret: str, *, at: float | None = None) -> str:
    """Compute the TOTP code for ``secret`` at the given time (defaults to now)."""
    if at is None:
        at = time.time()
    counter = int(at) // _PERIOD
    return _hotp(_b32decode_padded(secret), counter)


def verify_totp(secret: str, code: str, *, at: float | None = None) -> bool:
    """Constant-time check of ``code`` against ``secret``.

    Accepts the previous, current and next 30s windows (``±_DRIFT_WINDOWS``)
    to tolerate clock skew.

    Does **not** prevent replay — use :func:`verify_totp_and_counter` for
    that, which also returns the accepted counter so the caller can
    persist it and reject reuse.
    """
    return verify_totp_and_counter(secret, code, at=at) is not None


def verify_totp_and_counter(secret: str, code: str, *, at: float | None = None) -> int | None:
    """Return the counter for the matching window, or ``None`` if the
    code doesn't verify.

    The caller is expected to compare the returned counter against the
    user's stored high-water mark (``users.totp_last_counter``) and
    reject codes ``<=`` that to prevent replay within the same 30-second
    window (per RFC 6238 §5.2).
    """
    if not secret or not code:
        return None
    code = code.strip()
    if not code.isdigit() or len(code) != _DIGITS:
        return None
    if at is None:
        at = time.time()
    counter = int(at) // _PERIOD
    key = _b32decode_padded(secret)
    for delta in range(-_DRIFT_WINDOWS, _DRIFT_WINDOWS + 1):
        candidate_counter = counter + delta
        candidate = _hotp(key, candidate_counter)
        if hmac.compare_digest(candidate, code):
            return candidate_counter
    return None


def otpauth_url(secret: str, *, account: str, issuer: str = "Garant") -> str:
    """Return an ``otpauth://`` URL suitable for QR generation."""
    label = quote(f"{issuer}:{account}", safe="")
    return (
        f"otpauth://totp/{label}"
        f"?secret={secret}"
        f"&issuer={quote(issuer)}"
        f"&algorithm=SHA1"
        f"&digits={_DIGITS}"
        f"&period={_PERIOD}"
    )


# Environment override — when set, bypasses TOTP entirely so e2e tests
# can exercise treasury endpoints without provisioning a real secret.
_TOTP_BYPASS = os.environ.get("ADMIN_TOTP_BYPASS") or ""


async def _consume_totp(session: AsyncSession, user: User, code: str | None) -> None:
    """Verify ``code`` against ``user.totp_secret`` and atomically bump
    ``totp_last_counter`` so the same code can't be replayed inside its
    30-second window.

    Raises 401 on missing/invalid code, 403 if TOTP isn't configured.
    The bypass env var (``ADMIN_TOTP_BYPASS``) short-circuits both
    checks for e2e tests.
    """
    if _TOTP_BYPASS and code == _TOTP_BYPASS:
        return
    if not user.totp_enabled or not user.totp_secret:
        raise HTTPException(403, "2FA не настроен — пройдите настройку 2FA")
    if not code:
        raise HTTPException(401, "Введите код 2FA")
    matched = verify_totp_and_counter(user.totp_secret, code)
    if matched is None:
        raise HTTPException(401, "Неверный код 2FA")
    if matched <= (user.totp_last_counter or -1):
        # Replay: code already accepted in this (or an earlier) window.
        raise HTTPException(401, "Код 2FA уже использован — дождитесь следующего")
    user.totp_last_counter = matched
    session.add(user)


async def require_totp(
    user: AdminUser,
    session: SessionDep,
    x_totp_code: Annotated[str | None, Header(alias="X-Totp-Code")] = None,
) -> User:
    """FastAPI dependency that gates a route behind a valid TOTP code.

    Returns the resolved admin ``User`` so handlers don't have to
    re-declare ``AdminUser``. Raises 403 if TOTP isn't configured for
    the actor; 401 if the code is wrong, missing, or already used.

    The accepted code's counter is persisted on ``user.totp_last_counter``
    so the same 6-digit value can't be reused within its 30-second
    window. The change is staged on the dependency-injected session
    and committed by the route handler at the end of the transaction;
    if the handler raises, the bump rolls back, leaving the code
    consumable again — that's intentional (we only burn the code on
    success).
    """
    await _consume_totp(session, user, x_totp_code)
    return user


TotpUser = Annotated[User, Depends(require_totp)]
